sudo: true
dist: trusty

language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: mvnw package
      script:
      - ./mvnw package
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker-compose build
      - docker images
      - docker-compose push
    - stage: test
      script:
      - docker-compose up -d
      - ./dockerfiles/test.sh
      - docker-compose stop && echo y | docker-compose rm
    - stage: push docker image
      script:
      - docker-compose push
    - stage: deploy
      script:
      - echo "deploy"

notifications:
  email:
    recipients:
      - gaozhidf@foxmail.com