sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
  - chmod +x dockerfiles/*.sh

jobs:
  include:
    - stage: mvnw package
      script:
      - ./mvnw package
    - stage: build && test
      script:
      - docker-compose up --build -d
      - docker images
      - ./dockerfiles/test.sh
      - docker-compose down --rmi all
    - stage: push docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker-compose build
      - docker-compose push
    - stage: ansible deploy
      install: skip
      script:
      - openssl aes-256-cbc -K $encrypted_62f3167d5387_key -iv $encrypted_62f3167d5387_iv -in id_rsa.enc -out ./dockerfiles/ansible/id_rsa -d
      - chmod 600 ./dockerfiles/ansible/id_rsa
      - cp docker-compose.yml ./dockerfiles/ansible/
      - sed -i "s#\$TARGET_SERVER_HOST#$TARGET_SERVER_HOST:$TARGET_SERVER_PORT#g" ./dockerfiles/ansible/hosts
      - >
        docker run --privileged -e ANSIBLE_FORCE_COLOR=1 --rm
                   -v ./dockerfiles/ansible:/target_files/
                   williamyeh/ansible:alpine3
                   ansible-playbook --key-file /target_files/id_rsa -i /target_files/hosts /target_files/task.yml

notifications:
  email:
    recipients:
      - gaozhidf@foxmail.com