sudo: true
dist: trusty

language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: mvnw package
      script:
      - ./mvnw package
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t demo_ci .
      - docker images
      - docker tag demo_ci $DOCKER_USERNAME/demo_ci
      - docker push $DOCKER_USERNAME/demo_ci
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/demo_ci curl localhost:8080/hello
#    - script: docker run --rm $DOCKER_USERNAME/demo_ci cat hello.txt

notifications:
  email:
    recipients:
      - gaozhidf@foxmail.com