sudo: true
dist: trusty

language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
  - chmod +x dockerfiles/test.sh
  - openssl aes-256-cbc -K $encrypted_62f3167d5387_key -iv $encrypted_62f3167d5387_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

jobs:
  include:
    - stage: mvnw package
      script:
      - ./mvnw package
    - stage: build && test
      script:
      - docker-compose up --build -d
      - docker images
      - ./dockerfiles/test.sh
      - docker-compose down --rmi all
    - stage: push docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker-compose build
      - docker-compose push
    - stage: deploy
      script:
      - chmod 600 ~/.ssh/id_rsa
      - ssh travis@${DEPLOY_TARGET_SERVER} -o StrictHostKeyChecking=no 'cd ~ && wget https://github.com/${TRAVIS_REPO_SLUG}/blob/master/docker-compose.yml && docker-compose down --rmi all && docker-compose up --build -d'


notifications:
  email:
    recipients:
      - gaozhidf@foxmail.com